# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Setup the application"
  lane :setup do
    setup_specs_repo
    cocoapods
  end

  desc "Setup private specs repo"
  private_lane :setup_specs_repo do
    sh '../Scripts/setup_private_repo.sh'
  end
end
